# Terraform init, plan

steps:
- name: 'gcr.io/agmsb-k8s-ops/terraform'
  args: ['init',
    '-backend-config=project=agmsb-k8s-ops',
    '-backend-config=bucket=agmsb-terraform-state']
  env:
    - "TF_VAR_project-name=agmsb-k8s"
- name: 'gcr.io/agmsb-k8s-ops/terraform'
  args: ['plan']
  env:
    - "TF_VAR_project-name=agmsb-k8s"

# - name: 'gcr.io/agmsb-k8s-ops/terraform'
#  args: ['apply', '-auto-approve']
#  env:
#    - "TF_VAR_project-name=agmsb-k8s"
# - name: 'gcr.io/agmsb-k8s-ops/terraform'
#  args: ['destroy', '-auto-approve']
#  env:
#    - "TF_VAR_project-name=agmsb-k8s"